version: '3.8'

services:
  first_service:
    image: usermanager
    ports:
      - 3000:3000
    deploy:
      replicas: 3

  second_service:
    image: usermanager
    ports:
      - 3001:3000
    deploy:
      replicas: 2
